airlines/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('flights/',include("flights.urls")),
    path('users/',include("users.urls"))
]

flights/urls.py
from django.http.response import HttpResponse
from django.urls import path
from . import views
app_name="flights_app"
urlpatterns=[
    path('',views.index,name="index"),
    path('airports',views.airports1,name="airlines_airports"),
    path('<int:flight_id>',views.flights_id,name="flight_id"),
    path('<int:flight_id>/book',views.book,name="book"),
    path('allpassengers',views.allpassengers,name="all_passengers")
]

users/urls.py
from django.urls import path
from . import views

app_name="users"
urlpatterns=[
    path('',views.index,name="index"),
    path("login",views.login3,name="login"),
    path("logout",views.logout3,name="logout")
]

flights/models.py
from django.db import models
from django.db.models.fields import CharField
# Create your models here.

# class flights(models.Model):
#     origin=models.CharField(max_length=64)
#     destination=models.CharField(max_length=64)
#     duration=models.IntegerField()
#     def __str__(self):
#         return f"{self.id}:{self.origin} to {self.destination} in duration {self.duration}"

class airports(models.Model):
   
    city=models.CharField(max_length=64)
    code=models.CharField(max_length=64)
    def __str__(self):
        return f"{self.city} ({self.code})"
        

class flights(models.Model):
    origin=models.ForeignKey(airports,on_delete=models.CASCADE,related_name="departures")
    destination=models.ForeignKey(airports,on_delete=models.CASCADE,related_name="arrivals")
    duration=models.IntegerField()
    def __str__(self):
        return f"{self.origin} to {self.destination} in {self.duration}min"


class passengers(models.Model):
    first=models.CharField(max_length=64)
    last=models.CharField(max_length=64)
    flights6=models.ManyToManyField(flights,blank=True,related_name="passenger")
    def __str__(self):
        return f"{self.first} {self.last} "

users/models.py
from django.db import models

# Create your models here.

flights/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import flights,airports, passengers
from django.db import models
from django.urls import reverse


def index(request):
    return render(request,"flights/index.html",{
        "flights":flights.objects.all()
    })
def airports1(request):
    return render(request,"flights/airports.html",{
        "airports":airports.objects.all()
    })

def flights_id(request,flight_id):
    flight3=flights.objects.get(id=flight_id)
    passenger=passengers.objects.get(id=flight_id)
    passenger2=flight3.passenger.all()
    all_flight=flights.objects.all()
    return render(request,"flights/flights_id.html",{
        "flight_id":flight_id,
        "flights":flight3,
        "passenger":passenger2,
        "non_passengers":passengers.objects.exclude(flights6=flight3).all()
    })

def book(request,flight_id):
    if request.method=="POST" and not request.POST["passenger"]=="empty":
        f=flights.objects.get(pk=flight_id)
        passenger1=passengers.objects.get(pk=int(request.POST["passenger"]))
        passenger1.flights6.add(f)
        return HttpResponseRedirect(reverse("flights_app:flight_id",args=(flight_id,)))
    else:
        return HttpResponse("oops something went wrong")

def allpassengers(request):
    return render(request,"flights/allpassengers.html",{
        "all_passengers":passengers.objects.all()
    })

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
# Create your views here.


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("users:login"))
    else:
        return HttpResponseRedirect(reverse("flights_app:index"))


def login3(request):
    if request.method=="POST":
        username=request.POST["username"]
        password=request.POST["password"]
        user1=authenticate(request,password=password,username=username)
        if user1 is not None:
            login(request,user1) 
            return HttpResponseRedirect(reverse("users:index"))
        else:    
            return HttpResponseRedirect(reverse("users:login"),{
                "message":"invalid credentials"
            })
    return render(request,"users/login.html",{

    })

def logout3(request):
    logout(request)
    return HttpResponseRedirect(reverse("users:login"),{
        "logout_message":"logged out successfully"
    })

flights/templates/flights/airports.html
{% extends "flights/layout.html" %}
{%block body%}
    
       {% for x in airports %}
            <h2 style="color:orange; ">{{x}}</h2>
       {%endfor%}
 
{% endblock %}

flights/templates/flights/allpassengers.html
{% block body %}

{{all_passengers}}

{% endblock %}

flights/templates/flights/flights_id.html
{% extends "flights/layout.html" %}

{% block body %}
{{flights}} 
<ul class="ul">
{{flights.id}}
{{flights.origin.city}}
{{flights.destination.city}}
{{flights.duration}}
</ul>
<ul>
    {% for pass in passenger %}
        <h2>{{pass.first}} {{pass.name}}</h2>
    {%empty%}
    <H2> no passesngers</H2>
    {%endfor%}
</ul>
<h2>add passesngers</h2>
<form action="{% url 'flights_app:book' flights.id %} " method="post" >
    {% csrf_token %}
    <select name="passenger">
        {% for psg in non_passengers %}
       <option value="{{psg.id}}">{{psg}}</option>
       {% empty %}
        <option value="empty">empty passengers</option>
        {% endfor %}
    </select>
    <input type="submit" name="fname">
</form>
<a href="{% url 'flights_app:index' %}">back to flights</a>
{%endblock%}

flights/templates/flights/index.html
{% extends "flights/layout.html"  %}

{%block body%}

{% for x in flights %}
<h2 style="color:black;">
    <a href="{% url 'flights_app:flight_id' x.id %}" style="color:pink;">{{x}}</a>
</h2>
{%empty%}
<h2>nothing in the data base</h2>

{%endfor%}

{%endblock%}

flights/templates/flights/layout.html
<!DOCTYPE html>
<html lang="en">
    <html>
        <head>

            <title>Airlines</title>
        </head>
       <body>
        {% block body %}
 
          

        {% endblock %}

        <a href="{% url 'users:logout' %}" style="color:rgb(95, 95, 173);">logout</a>

        </body>
    </html>

users/templates/users/layout.html
<!DOCTYPE html>
<html lang="en">
    <html>
        <head>
            <title>users_app</title>
            </head>
        <body>
            {% block body %}



            {% endblock %}
        </body>
        </html>

users/templates/users/login.html
{% extends "users/layout.html" %}

{% block body%}

{% if logout_message is not None %}
<div style="color: green;">{{logout_message}}</div>
{% endif %}


<form action="{% url 'users:login' %}" method="POST" name="login">
    {% csrf_token %}
    <input type="text" name="username">
    <input type="password" name="password">
    <input type="submit" name="login">
</form>

{% if message %}
<div style="color: red;">{{message}}</div>
{% endif %}

{% endblock%}